import type { Metadata } from 'next';
import './globals.css';

import MainNavigation from './components/Navigation/Menu/MainMenu';

export const metadata: Metadata = {
  title: '404HERTZ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
