import type { Metadata } from 'next';
import './globals.css';

import MainNavigation from './components/Navigation/Menu/MainMenu';

import { createClient } from '@/prismicio';
import { Providers } from './components/Providers/Providers';

export const metadata: Metadata = {
  title: '404HERTZ',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();

  const icons = await client.getAllByType('social_icons');

  return (
    <html lang="en">
      <body>
        <Providers icons={icons}>
          <MainNavigation />
          {children}{' '}
        </Providers>
      </body>
    </html>
  );
}
